//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerManagement.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public int Id { get; set; }
        public int ActivityType { get; set; }
        public string TableName { get; set; }
        public Nullable<int> DataId { get; set; }
        public int UserId { get; set; }
        public string IpAddress { get; set; }
        public string MacAddress { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool Active { get; set; }
    
        public virtual User User { get; set; }
    }
}
