//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerManagement.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Server
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string HostName { get; set; }
        public string IP1 { get; set; }
        public string IP2 { get; set; }
        public string IP3 { get; set; }
        public string IP4 { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Functionality { get; set; }
        public bool Active { get; set; }
    }
}
